# Generated by Django 2.1.5 on 2019-01-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('inventory_count', models.IntegerField(default=0)),
            ],
        ),
    ]
